apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-deploy
  name: jenkins-deploy
spec:
  ports:
  - port: 8080
    nodePort: 30001
    targetPort: 8080
  selector:
    app: jenkins-deploy
  type: NodePort
